version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stock-backend
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=stock_db
      - DB_USERNAME=stock_user
      - DB_PASSWORD=stock_password
    networks:
      - stock-network

  webserver:
    image: nginx:alpine
    container_name: stock-nginx
    restart: unless-stopped
    ports:
      - "3034:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app
    networks:
      - stock-network

  db:
    image: postgres:15
    container_name: stock-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: stock_db
      POSTGRES_USER: stock_user
      POSTGRES_PASSWORD: stock_password
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - stock-network

networks:
  stock-network:
    driver: bridge

volumes:
  dbdata:
    driver: local 